add more apks

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -99,6 +99,14 @@ jobs:
           echo "List of folders in my_heytap/priv-app"
           ls -l mnt/my_heytap/priv-app
           echo
+          # list folders in my_stock/app
+          echo "List of folders in my_stock/app"
+          ls -l mnt/my_stock/app
+          echo
+          # list folders in my_heytap/app
+          echo "List of folders in my_heytap/app"
+          ls -l mnt/my_heytap/app
+          echo
 
           # update files
           if [ -d product ]; then
@@ -107,6 +115,7 @@ jobs:
           if [ -d system ]; then
             rm -rf system
           fi
+
           mkdir -p product/priv-app
           cp -r mnt/my_stock/priv-app/KeKeUserCenter product/priv-app/
           cp -r mnt/my_stock/priv-app/KeKeUserCenterAccount product/priv-app/
@@ -116,6 +125,24 @@ jobs:
             cp -r mnt/my_stock/priv-app/OpenID product/priv-app/
           else
             echo "OpenID not found"
+            exit 1
+          fi
+
+          mkdir -p product/app
+          if [ -d mnt/my_heytap/app/KeKePay ]; then
+            cp -r mnt/my_heytap/app/KeKePay product/app/
+          elif [ -d mnt/my_stock/app/KeKePay ]; then
+            cp -r mnt/my_stock/app/KeKePay product/app/
+          else
+            echo "KeKePay not found"
+            exit 1
+          fi
+          if [ -d mnt/my_heytap/app/TasWallet ]; then
+            cp -r mnt/my_heytap/app/TasWallet product/app/
+          elif [ -d mnt/my_stock/app/TasWallet ]; then
+            cp -r mnt/my_stock/app/TasWallet product/app/
+          else
+            echo "TasWallet not found"
             exit 1
           fi
           
